// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20241128082046_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("103c8287-30cb-4630-c3f2-978286f72bd7"),
                            AccountType = "AccountType1",
                            DateCreated = new DateTime(2024, 11, 28, 8, 20, 46, 559, DateTimeKind.Utc).AddTicks(2640),
                            OwnerId = new Guid("103c8287-30cb-4630-b3f2-978286f72bd7")
                        },
                        new
                        {
                            Id = new Guid("103c8287-30cb-4630-c3f2-978286f72bd8"),
                            AccountType = "AccountType2",
                            DateCreated = new DateTime(2024, 11, 28, 8, 20, 46, 559, DateTimeKind.Utc).AddTicks(2642),
                            OwnerId = new Guid("103c8287-30cb-4630-b3f2-978286f72bd7")
                        },
                        new
                        {
                            Id = new Guid("103c8287-30cb-4630-c3f2-978286f72bd9"),
                            AccountType = "AccountType3",
                            DateCreated = new DateTime(2024, 11, 28, 8, 20, 46, 559, DateTimeKind.Utc).AddTicks(2644),
                            OwnerId = new Guid("103c8287-30cb-4630-b3f2-978286f72bd8")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Owner", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("103c8287-30cb-4630-b3f2-978286f72bd7"),
                            Address = "Cairo,Egypt",
                            DateOfBirth = new DateTime(1996, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OwnerSedded"
                        },
                        new
                        {
                            Id = new Guid("103c8287-30cb-4630-b3f2-978286f72bd8"),
                            Address = "Alex,Egypt",
                            DateOfBirth = new DateTime(1997, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OwnerSedded2"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.HasOne("Domain.Entities.Owner", null)
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Owner", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
